### ISSUE TITLE
Jupiter v1.3

### ISSUE THREAD

**Issue by fengjiachun** [fengjiachun/Jupiter#79]
## TODO LIST：

- [x] 不再支持 java7，仅支持 java8 及以上版本，需要支持 java11
- [x] 移除 AbstractFuture，直接使用 java8 的CompletableFuture
- [x] ReadWriteLock -> StampedLock
- [x] InvokeType.AUTO #82 
- [ ] Pipeline invoke #83 
- [ ] Benchmark client  支持流式请求 #86 
- [ ] 增加 Batch decoder #84 
- [ ] 更完善的单测
- [ ] 还有一些慢慢补充
